#!/bin/sh
#
# Xcode Cloud custom build script — runs after the repository is cloned.
# Generates ios/Trunk/Config/Secrets.swift (which is gitignored) so the cloud
# build compiles. Real Supabase credentials come from Xcode Cloud *secret*
# environment variables SUPABASE_URL / SUPABASE_ANON_KEY set on the workflow.
# If they are unset (e.g. a test-only workflow), it writes the same "xxxxx" /
# "..." placeholders SupabaseClient.swift treats as "not configured", so the
# app still builds and runs offline.
#
set -eu

# In Xcode Cloud the checked-out repo root is CI_PRIMARY_REPOSITORY_PATH.
# Locally (dry run) fall back to two levels up from this script: repo/ios/ci_scripts -> repo.
ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}"
SECRETS="$ROOT/ios/Trunk/Config/Secrets.swift"

# Secrets.swift is committed (the anon key is a public RLS-protected client key),
# so in a normal build it's already here — don't overwrite it. The generation
# below is only a fallback for checkouts where it's absent.
if [ -f "$SECRETS" ]; then
  echo "ci_post_clone: Secrets.swift already present — using committed config."
  exit 0
fi

URL="${SUPABASE_URL:-https://xxxxx.supabase.co}"
ANON="${SUPABASE_ANON_KEY:-ci-placeholder-anon-key-...}"

mkdir -p "$(dirname "$SECRETS")"
cat > "$SECRETS" <<EOF
// Auto-generated by ci_scripts/ci_post_clone.sh — do NOT commit.
// Real values are injected from Xcode Cloud secret environment variables.
enum Secrets {
    static let supabaseURL = "$URL"
    static let supabaseAnonKey = "$ANON"
}
EOF

if [ -n "${SUPABASE_ANON_KEY:-}" ] && [ -n "${SUPABASE_URL:-}" ]; then
  echo "ci_post_clone: wrote Secrets.swift with injected Supabase config."
else
  echo "ci_post_clone: SUPABASE_URL/SUPABASE_ANON_KEY not set — wrote placeholder Secrets.swift (offline build)."
fi
